### ISSUE TITLE
Future of this project vs HackMD.io's TypeScript CodiMD-CLI

### ISSUE THREAD

**Issue by pirate** [codimd/cli#34]
@SISheogorath what are your thoughts on keeping this separate from https://github.com/hackmdio/codimd-cli/ ?

It seems like there's more development resources available to go into the other project, and it seems better suited to be the long-term CLI solution compared to my janky bash script.

**Comment by pirate** [comment]
For now I added a link to the README: https://github.com/codimd/cli/commit/412285e4c01f7b95858504f14f09dc4acd7b0ee4

**Comment by SISheogorath** [comment]
To be honest I'm not a fan of this idea. I don't expect their CLI to be compatible with 2.0 of our version of CodiMD and things will break in long term. Therefore, I actually prefer your "janky bash script".

Also, don't underestimate a bash script as look at what great pieces of software are written in bash? [`pass`](https://www.passwordstore.org/) is just one example.

**Comment by davidak** [comment]
I'm also not a fan of this idea.

good points for this bash script:

1. users on macOS and linux can just run it, on windows using WSL or Cygwin. JS stuff is hard to install for normal users
2. we would be dependent on HackMD team to implement the script in the way we need it
3. in long term, i would prefer that a script is not needed and everything can be done in the web UI. that will make the software more accessible to people scared of the terminal. terminal wizards can still have their scripts 🧙

But yes, bash can become very nasty to maintain when it get's bigger. So i suggest everyone to use Python instead for everything more than 5 lines. Here is a german talk about that: https://media.ccc.de/v/GLT18_-_336_-_de_-_g_ap147_006_-_201804281245_-_python_statt_shell-scripts_-_thomas_aglassinger

@pirate can you add some words about compatibility next to the link? and have you tested it actually?

**Comment by pirate** [comment]
Ah sure, I assumed ya'll would be happier with the NPM script than bash, but I'm a huge bash fan myself and I have no problem keeping this bash repo alive separately if that's the consensus :)

I don't have much dev time to offer I'm afraid, but I don't mind reviewing PRs & issues and making the occasional contribution to keep pushing this version forward.

**Comment by davidak** [comment]
>One note is that I disagree with your point #3 @davidak, there is lots of stuff that needs to be doable via CLI in order for CodiMD to be versatile and competitive compared to other solutions

>I think having a good REST API or CLI is essential, even if 95% of users don't need it.

I fully agree. My point is, that these "95% of users" should not need to use a CLI to use the software.

My big plan is to make good free software more accessible, so more people can use it. And when the projects communicate the need reasonable, they will get funding from users and the maintainers can work full-time on it, what makes the software even better, for everyone. You can see that this works when you look at the success of Patreon and OpenCollective! (I don't say anyone should use these for-profit companies) I work on practical recommendations for projects to do so, but it's not ready yet.

That's why i argue for improving the user experience even tho i'm able to use the CLI myself.
